import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarTop from "@/components/ui/navbar-top";
import NavbarLink from "@/components/ui/navbar-link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavbarTop>
          <NavbarLink href="/dashboard">Dashboard</NavbarLink>
          <NavbarLink href="/calendar">Calendar</NavbarLink>
        </NavbarTop>
        {children}
      </body>
    </html>
  );
}
