import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/navbar/navbar";
import NavbarDropdown from "@/components/ui/navbar/navbar-dropdown";
import Link from "next/link";
import NavbarLink, { NavbarLinks, verticalNavbarLinkStyles } from "@/components/ui/navbar/navbar-link";
import UserDropdown from "@/components/ui/user-dropdown";

export const metadata: Metadata = {
  title: "Planner",
  description: "Next.js planner application Generated by create next app",
};

export default function RootLayout({
  children,
  auth
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Navbar>
          <NavbarLinks links={[
            { name: "Home", href: "/" },
            { name: "Dashboard", href: "/dashboard" },
            { name: "Calendar", href: "/calendar"},
            { name: "Todo", href: "/todo" },
          ]} />
          
          <UserDropdown />
        </Navbar>
        <div>{auth}</div>
        <div className="container mx-auto my-16">{children}</div>
      </body>
    </html>
  );
}
