import type { Metadata } from "next";
import "./globals.css";
import { NavbarLinks } from "@/components/ui/navbar/NavbarLink";
import UserDropdown from "@/components/ui/UserDropdown";
import Navbar from "@/components/ui/navbar/Navbar";

export const metadata: Metadata = {
  title: "Planner",
  description: "Next.js planner application Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Navbar>
          <NavbarLinks links={[
            { name: "Home", href: "/" },
            { name: "Dashboard", href: "/dashboard" },
            { name: "Calendar", href: "/calendar"},
            { name: "Todo", href: "/todo" },
          ]} />
          
          <UserDropdown />
        </Navbar>
        <div className="container mx-auto my-16">{children}</div>
      </body>
    </html>
  );
}
